# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Non-Stationary Bandit Problem
#'
#' @description
#' A function to simulate rewards and means for a non-stationary multi-armed bandit problem.
#'
#' @param N  Integer. Number of arms.
#' @param T Integer. Number of rounds.
#' @param sigma Numeric. Standard deviation of the rewards.
#' @param delta Numeric. Drift standard deviation.
#' @param mu Numeric vector. Initial means for each arm.
#' @import boot
#' @import coda
#' @importFrom ggplot2 ggplot
#' @import microbenchmark
#' @return A numeric matrix of rewards for each arm across all rounds.
#' @export

simulate_bandit <- function(N, T, sigma, delta, mu) {
    .Call('_BL22204010_simulate_bandit', PACKAGE = 'BL22204010', N, T, sigma, delta, mu)
}

